version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
- package-ecosystem: pip
  directory: /
  schedule:
    interval: monthly
  groups:
    minor-bumps:
      applies-to: version-updates
      patterns:
      - '*'
      update-types:
      - minor
      - patch
